[package]
name = "jungle_gem"
version = "1.0.0"
authors = []

[addresses]
jungle_gem = "f7b0dbf827ef89e261539f6c6742ecf0268992b71a9a651c03d7742b1574bdb7"
jungle_gem_default_admin = "62647058b3c06582fc3bbac4ace42d0bd1e1a21adbaf6a8e6d63d7ed7039be6b"
jungle_gem_dev = "62647058b3c06582fc3bbac4ace42d0bd1e1a21adbaf6a8e6d63d7ed7039be6b"
null_address = "0x0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-token"
