[package]
name = "jungle_run"
version = "1.0.0"
authors = []

[addresses]
jungle_run = "8d30ec385d45c6ad43f39e857c2d17896eadcbed9ea201ad72ae3aea9ad3452b"
jungle_run_default_admin = "baa4882c050dd32d2405e9c50eecd308afa1cf4f023e45371671a60a051ea500"
jungle_run_dev = "baa4882c050dd32d2405e9c50eecd308afa1cf4f023e45371671a60a051ea500"
null_address = "0x0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"


