[package]
name = "jungle_run"
version = "1.0.0"
authors = []

[addresses]
jungle_run = "80ecb10bc51544c131b74e90a33977ed99378f56065d964f5d17b961674d82af"
jungle_run_default_admin = "64a8da9a54436e45a94bd9059462f4c2c60acf1d81f4a27b68ad02a86e20c1ec"
jungle_run_dev = "64a8da9a54436e45a94bd9059462f4c2c60acf1d81f4a27b68ad02a86e20c1ec"
null_address = "0x0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"


